apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
  labels:
    app: object-detection
spec:
  selector:
    matchLabels:
      app: object-detection
  replicas: 1
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
        - name: object-detection
          image: sampreethamithkumar/object_detection_instance_build:1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
  labels:
    app: object-detection
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: object-detection
